"""rollback index

Revision ID: e93090f190f7
Revises: f7ac91c1eb0f
Create Date: 2025-12-03 14:19:34.660460

"""

from typing import Sequence, Union


from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e93090f190f7"
down_revision: Union[str, Sequence[str], None] = "f7ac91c1eb0f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_events_event_data"), table_name="events")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f("ix_events_event_data"), "events", ["event_data"], unique=False)
    # ### end Alembic commands ###
