"""rollback_test

Revision ID: ea1cdc332a39
Revises: f478e171cdee
Create Date: 2025-12-03 14:16:46.316862

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'ea1cdc332a39'
down_revision: Union[str, Sequence[str], None] = 'f478e171cdee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
	"""Upgrade schema."""
	# ### commands auto generated by Alembic - please adjust! ###
	op.drop_column('events', 'user')
	# ### end Alembic commands ###


def downgrade() -> None:
	"""Downgrade schema."""
	# ### commands auto generated by Alembic - please adjust! ###
	op.add_column('events', sa.Column('user', mysql.VARCHAR(length=50), nullable=False))
	# ### end Alembic commands ###
