"""test_index

Revision ID: f7ac91c1eb0f
Revises: ea1cdc332a39
Create Date: 2025-12-03 14:19:12.085823

"""

from typing import Sequence, Union


from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'f7ac91c1eb0f'
down_revision: Union[str, Sequence[str], None] = 'ea1cdc332a39'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
	"""Upgrade schema."""
	# ### commands auto generated by Alembic - please adjust! ###
	op.create_index(op.f('ix_events_event_data'), 'events', ['event_data'], unique=False)
	# ### end Alembic commands ###


def downgrade() -> None:
	"""Downgrade schema."""
	# ### commands auto generated by Alembic - please adjust! ###
	op.drop_index(op.f('ix_events_event_data'), table_name='events')
	# ### end Alembic commands ###
